[package]
name = "poker"
version = "0.1.0"
authors = ["yky4n4g1 <yky4n4g1@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
